version: '2'
services:
    allsportynews-app:
        image: allsportynews
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://allsportynews-mysql:3306/allsportynews?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=allsportynews-elasticsearch:9300
        ports:
            - 8080:8080
    allsportynews-mysql:
        extends:
            file: mysql.yml
            service: allsportynews-mysql
    allsportynews-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: allsportynews-elasticsearch
